using System;
using UnityEditor;
using UnityEngine;

namespace Crescendo.API.Editor {

    public enum NameType {
        SurnameFirst,
        SurnameLast
    }

    public class CharacterEditorData : ScriptableObject {
        
        private const string CharacterRootFolder = "Characters";
        private const string GeneratedFolderName = "_Autogenerated";
        private const string RuntimeDataSuffix = "_data";

        [SerializeField]
        private string _firstName = "Marisa";

        [SerializeField]
        private string _lastName = "Kirisame";

        [SerializeField]
        private NameType _nameType = NameType.SurnameLast;
  
        private CharacterData _runtimeData;

        public string FirstName {
            get { return _firstName; }
            set { _firstName = value; }
        }

        public string LastName {
            get { return _lastName; }
            set { _lastName = value; }
        }

        public NameType NameStyle {
            get { return _nameType; }
            set { _nameType = value; }
        }

        public string FullName {
            get {
                if (String.IsNullOrEmpty(_firstName))
                    return _lastName;
                if (String.IsNullOrEmpty(_lastName))
                    return _firstName;
                if (_nameType == NameType.SurnameFirst)
                    return LastName + " " + FirstName;
                return FirstName + " " + LastName;
            }
        }

        public string InternalName {
            get { return name; }
            set { name = value; }
        }

        public string CharacterDataFolder {
            get { return AssetUtil.CreateAssetPath(CharacterRootFolder); }
        }

        public string RootFolder {
            get { return AssetUtil.CreateAssetPath(CharacterRootFolder, InternalName); }
        }

        public string GeneratedFolder {
            get { return AssetUtil.CreateAssetPath(CharacterRootFolder, InternalName, GeneratedFolderName); }
        }

        public string RuntimeResources {
            get { return AssetUtil.CreateAssetPath(CharacterRootFolder, InternalName, GeneratedFolderName, "Resources"); }
        }

        public CharacterData RuntimeData {
            get {
                if(_runtimeData == null)
                    _runtimeData = Resources.Load<CharacterData>(InternalName + RuntimeDataSuffix);
                return _runtimeData;
            }
        }

        public void Generate() {
            //If this object is not an asset
            AssetUtil.CreateAsset(RootFolder, this);

            //Create the Runtime Resources folder if it doesn't already exist
            AssetUtil.CreateFolder(RuntimeResources);

            if (RuntimeData == null) {
                CharacterData temp = ScriptableObject.CreateInstance<CharacterData>();
                temp.name = InternalName + RuntimeDataSuffix;
                AssetUtil.CreateAsset(RuntimeResources, temp);
            }

        }

    }

}
