using System.IO;
using System.Text.RegularExpressions;
using Hourai.Editor;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

namespace Hourai.SmashBrew.Editor {

    [InitializeOnLoad]
    public static class SmashBrewEditor {

        static SmashBrewEditor() {
            GenerateAutogeneratedFiles();
        }

        private static void GenerateAutogeneratedFiles() {
            foreach (string path in AssetUtil.FindAssetPaths<CharacterEditorData>())
                AssetDatabase.LoadAssetAtPath<CharacterEditorData>(path).Generate();
        }

        #region Asset Create Menu Items

        [MenuItem("Assets/Create/SmashBrew/Config")]
        static void CreateConfig() {
            AssetUtil.CreateAssetInProjectWindow<SmashConfig>();
        }

        #endregion
      
    }

}