using System;
using UnityEngine;


namespace HouraiTeahouse.HouraiInput {
    public class UnityInputDeviceProfileList : ScriptableObject {
        public static string[] Profiles = new string[] {
            "HouraiTeahouse.HouraiInput.AmazonFireTVProfile",
            "HouraiTeahouse.HouraiInput.AmazonFireTVRemote",
            "HouraiTeahouse.HouraiInput.AndroidTVProfile",
            "HouraiTeahouse.HouraiInput.AndroidTVRemoteProfile",
            "HouraiTeahouse.HouraiInput.AppleMFiProfile",
            "HouraiTeahouse.HouraiInput.ExecutionerXProfile",
            "HouraiTeahouse.HouraiInput.GameStickLinuxProfile",
            "HouraiTeahouse.HouraiInput.GameStickProfile",
            "HouraiTeahouse.HouraiInput.GenericAndroidProfile",
            "HouraiTeahouse.HouraiInput.GenericBlackBerryProfile",
            "HouraiTeahouse.HouraiInput.GenericLinuxProfile",
            "HouraiTeahouse.HouraiInput.GoogleNexusPlayerProfile",
            "HouraiTeahouse.HouraiInput.GoogleNexusPlayerRemoteProfile",
            "HouraiTeahouse.HouraiInput.GreenThrottleAtlasAndroidProfile",
            "HouraiTeahouse.HouraiInput.HamaBlackForceWinProfile",
            "HouraiTeahouse.HouraiInput.LogitechF310LinuxProfile",
            "HouraiTeahouse.HouraiInput.LogitechF310ModeDMacProfile",
            "HouraiTeahouse.HouraiInput.LogitechF310ModeDWinProfile",
            "HouraiTeahouse.HouraiInput.LogitechF310ModeXMacProfile",
            "HouraiTeahouse.HouraiInput.LogitechF310ModeXWinProfile",
            "HouraiTeahouse.HouraiInput.LogitechF510LinuxProfile",
            "HouraiTeahouse.HouraiInput.LogitechF510WinProfile",
            "HouraiTeahouse.HouraiInput.LogitechF710LinuxProfile",
            "HouraiTeahouse.HouraiInput.LogitechF710MacProfile",
            "HouraiTeahouse.HouraiInput.LogitechF710ModeDWinProfile",
            "HouraiTeahouse.HouraiInput.LogitechF710ModeXWinProfile",
            "HouraiTeahouse.HouraiInput.LogitechRumblePad2MacProfile",
            "HouraiTeahouse.HouraiInput.LogitechRumblePad2WinProfile",
            "HouraiTeahouse.HouraiInput.LogitechWingManWinProfile",
            "HouraiTeahouse.HouraiInput.MaxFireBlaze5Profile",
            "HouraiTeahouse.HouraiInput.MayflashGameCubeWinProfile",
            "HouraiTeahouse.HouraiInput.MogaProLinuxProfile",
            "HouraiTeahouse.HouraiInput.MogaProMacProfile",
            "HouraiTeahouse.HouraiInput.MogaProWinProfile",
            "HouraiTeahouse.HouraiInput.NVidiaShieldAndroidProfile",
            "HouraiTeahouse.HouraiInput.NVidiaShieldTabletProfile",
            "HouraiTeahouse.HouraiInput.NatecGenesisP44Profile",
            "HouraiTeahouse.HouraiInput.OuyaLinuxProfile",
            "HouraiTeahouse.HouraiInput.OuyaWinProfile",
            "HouraiTeahouse.HouraiInput.PlayStation2WinProfile",
            "HouraiTeahouse.HouraiInput.PlayStation3AndroidProfile",
            "HouraiTeahouse.HouraiInput.PlayStation3LinuxProfile",
            "HouraiTeahouse.HouraiInput.PlayStation3MacProfile",
            "HouraiTeahouse.HouraiInput.PlayStation3ShenghicWinProfile",
            "HouraiTeahouse.HouraiInput.PlayStation3WinProfile",
            "HouraiTeahouse.HouraiInput.PlayStation4AndroidProfile",
            "HouraiTeahouse.HouraiInput.PlayStation4LinuxProfile",
            "HouraiTeahouse.HouraiInput.PlayStation4MacBTProfile",
            "HouraiTeahouse.HouraiInput.PlayStation4MacUSBProfile",
            "HouraiTeahouse.HouraiInput.PlayStation4Profile",
            "HouraiTeahouse.HouraiInput.PlayStation4WinProfile",
            "HouraiTeahouse.HouraiInput.PlayStationVitaPSMProfile",
            "HouraiTeahouse.HouraiInput.SamsungGP20AndroidProfile",
            "HouraiTeahouse.HouraiInput.SpeedlinkStrikeMacProfile",
            "HouraiTeahouse.HouraiInput.SpeedlinkStrikeWinProfile",
            "HouraiTeahouse.HouraiInput.SteelSeriesFreeLinuxProfile",
            "HouraiTeahouse.HouraiInput.SteelSeriesFreeMacProfile",
            "HouraiTeahouse.HouraiInput.SteelSeriesFreeWinProfile",
            "HouraiTeahouse.HouraiInput.ValveStreamingWinProfile",
            "HouraiTeahouse.HouraiInput.Xbox360AndroidProfile",
            "HouraiTeahouse.HouraiInput.Xbox360LinuxProfile",
            "HouraiTeahouse.HouraiInput.Xbox360MacProfile",
            "HouraiTeahouse.HouraiInput.Xbox360WinProfile",
            "HouraiTeahouse.HouraiInput.XboxOneMacProfile",
            "HouraiTeahouse.HouraiInput.XboxOneProfile",
            "HouraiTeahouse.HouraiInput.XboxOneWinProfile",
        };
    }
}
